<?php
// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';

$client = new Updater("https://github.com/cwicaksono/android_news_app", "");

// print_r($client);
// $client = new \Github\Client();
// $repositories = $client->api('user')->repositories('ornicar');

// https://api.github.com/repos/cwicaksono/android_news_app/branches
// https://github.com/yazir-reinovasi/ojkway
//
// token: 472c719fdaedb10f06bad06a2d20b5f3a67ab0e7
/*
TODO - get repo commit message
TODO - if is_update: return to download zip, else: your repository is latest
TODO - download zip
*/
?>
